development:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5
  username: letladi
  password: letladi

test:
  adapter: postgresql
  encoding: unicode
  database: yelp_test
  pool: 5
  username: letladi
  password: letladi